services:
  postgres:
    image: postgres:16
    container_name: cube_postgres
    environment:
      POSTGRES_USER: cube
      POSTGRES_PASSWORD: cube
      POSTGRES_DB: cube
    ports:
      - "5432:5432"
    volumes:
      - cube_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: cube_redis
    ports:
      - "6379:6379"

volumes:
  cube_pg_data:
